language: python

python: 3.8

jobs:
  include:
    # perform a linux build
    - services: docker
      env:
        - COVER="on"
        - PYTHON=python3
        - PIP=pip3
    # and a mac build
    - os: osx
      language: shell
      env:
        - COVER="off"
        - PYTHON=python3
        - PIP=pip3
    # and a windows build
    - os: windows
      language: shell
      env:
        - COVER="off"
        - PYTHON=python
        - PIP=pip
      before_install:
        - choco install python --version 3.8.0
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"

env:
  global:
    - TWINE_USERNAME=mcuntz
    # Note: TWINE_PASSWORD is set in Travis settings

install:
  - $PYTHON -m $PIP install -U pip
  - $PYTHON -m $PIP install -U setuptools
  - $PYTHON -m $PIP install -U pytest
  - $PYTHON -m $PIP install -U pytest-cov
  - $PYTHON -m $PIP install -U coveralls
  - $PYTHON -m $PIP install -r tests/requirements_test.txt
  - $PYTHON -m $PIP install -r docs/requirements.txt
  - $PYTHON -m $PIP install cibuildwheel
  - $PYTHON -m $PIP install twine

script:
  # create wheels
  - $PYTHON -m cibuildwheel --output-dir wheelhouse
  # create source dist for pypi and create coverage
  - |
    if [[ $COVER == "on" ]] ; then
      $PYTHON -m $PIP install -U pytest
      $PYTHON -m $PIP install -U pytest-cov
      $PYTHON -m $PIP install -U coveralls
      $PYTHON -m $PIP install -r tests/requirements_test.txt
      rm -rf dist
      $PYTHON setup.py sdist
      export PYTHONPATH=${PYTHONPATH}:${PWD}
      $PYTHON -m pytest --cov hesseflux --cov-report term-missing -v tests/
      $PYTHON -m coveralls
    fi

after_success:
  # pypi upload (test always, official on TAG)
  - $PYTHON -m $PIP install -U twine
  - $PYTHON -m twine upload --verbose --skip-existing --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
  - |
    if [[ $COVER == "on" ]] ; then
      $PYTHON -m twine upload --verbose --skip-existing --repository-url https://test.pypi.org/legacy/ dist/*.tar.gz
    fi
  - |
    if [[ $TRAVIS_TAG ]] ; then
      $PYTHON -m twine upload --skip-existing wheelhouse/*.whl
      if [[ $COVER == "on" ]] ; then
        $PYTHON -m twine upload --skip-existing dist/*.tar.gz
      fi
    fi

notifications:
  email:
    recipients:
    - mc@macu.de
